name: devtestPoint
version: '1.0'
main: net.shini9000.devtestPoint.DevtestPoint
api-version: '1.21'
load: STARTUP
authors: [ Shini9000 ]
description: devtest for SAOWorld
website: https://github.com/shini9000/devtestPoint

commands:
  kit:
    description: Kit command
    permission: devtest.kit
    permission-message: You lack permission!
    usage: /<command> [Kit Name]
  points:
    description: Points command
    permission: devtest.points
    permission-message: You lack permission!
    usage: /<command> [PlayerName]
  top:
    description: Top command
    permission: devtest.top
    permission-message: You lack permission!
    usage: /<command> [PlayerName]
  zone:
    description: Top command
    permission: devtest.zone
    permission-message: You lack permission!
    usage: /<command> [PlayerName]

permissions:
  devtest.kit:
    description: Allows kit command
    default: true
  devtest.points:
    description: Allows kit command
    default: true
  devtest.top:
    description: Allows kit command
    default: true
  devtest.zone:
    description: Allows kit command
    default: op
  devtest.*:
      description: Wildcard perm
      default: op
